### ISSUE TITLE
CRITICAL:root:'ascii' codec can't encode character u'\xb5' in position 15: ordinal not in range(128)

### ISSUE THREAD

**Issue by jamesmulcahy** [grafana/grafana-tools#4]
This occurs because the file handled opened for writing isn't support utf-8.  I have a fix, which I'll push shortly.

**Comment by fessyfoo** [comment]
this can be closed. 

fixed by #5 and #6  2e1ae838492c553fe84b4d9e42b6789ecb6d8d11   (now merged)
